[package]
name = "runkillrun"
description = "*Run* an executable Program. When the exe file changes *kill* the old process. *Run* the new exe again."
version = "0.2.0" # keep in synch with flake.nix package version
edition = "2021"

[[bin]]
name = "rkr"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
