on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: build
        run: |
          apt install nix
          nix flake build
          nix flake check

